Vagrant.configure("2") do |config|
    config.vm.define "httpd" do |httpd|
        httpd.vm.box = "centos/7"
        httpd.vm.network "private_network", ip: "192.168.0.50"
    end

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
    end
    
    config.vm.provision "shell", path: "httpd.sh"
end